### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by re-jas** [abhijith365/simple_login_admin_page_node_js#1]
i can't login as admin. i checked mongodb and there is no info about admin but i can find info about users. please could you explain how you loged in as admin?

**Comment by abhijith365** [comment]
I upload a admin name and  encrypted password in MongoDB directly

**Comment by re-jas** [comment]
> I upload a admin name and encrypted password in MongoDB directly

please could you explain how to do that

**Comment by abhijith365** [comment]
add directly into MongoDB use MongoDB compass ,  you can remove encrypt code from admin, then add normal password to database and you can login as admin
